<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container69NEYYP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container69NEYYP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container69NEYYP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container69NEYYP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container69NEYYP\App_KernelDevDebugContainer([
    'container.build_hash' => '69NEYYP',
    'container.build_id' => '5408e43d',
    'container.build_time' => 1607542329,
], __DIR__.\DIRECTORY_SEPARATOR.'Container69NEYYP');
